# Generated by Django 4.1.1 on 2022-09-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ournews',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='article content'),
        ),
        migrations.AlterField(
            model_name='ournews',
            name='type',
            field=models.CharField(choices=[('1', 'story'), ('2', 'job'), ('3', 'comment'), ('4', 'poll'), ('5', 'pollopt')], default=1, max_length=10, verbose_name='article type'),
        ),
    ]
