# Generated by Django 4.1.1 on 2022-09-22 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapi', '0002_alter_ournews_content_alter_ournews_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_id', models.IntegerField(verbose_name='Unique ID')),
                ('score', models.IntegerField(verbose_name='News Score')),
                ('time_created', models.DateTimeField(auto_now=True, verbose_name='time created')),
                ('title', models.CharField(max_length=50, verbose_name='article title')),
                ('type', models.CharField(choices=[('1', 'story'), ('2', 'job'), ('3', 'comment'), ('4', 'poll'), ('5', 'pollopt')], default=1, max_length=10, verbose_name='article type')),
                ('url', models.URLField(verbose_name='Article link')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
