# Generated by Django 4.1.1 on 2022-09-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0003_hnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hnew',
            name='by',
        ),
    ]
