# Generated by Django 4.1.1 on 2022-09-23 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapi', '0004_remove_hnew_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewHNStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hn_id', models.IntegerField(verbose_name='HN unique ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='hnew',
            name='pk_id',
        ),
        migrations.AddField(
            model_name='hnew',
            name='by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
            preserve_default=False,
        ),
    ]
