# Generated by Django 4.1.1 on 2022-09-23 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0005_newhnstories_remove_hnew_pk_id_hnew_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hnew',
            name='pk_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newsapi.newhnstories', verbose_name='HN Unique ID'),
        ),
    ]
