# Generated by Django 4.1.1 on 2022-09-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0006_hnew_pk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hnew',
            name='by',
            field=models.CharField(max_length=50, verbose_name='Author'),
        ),
    ]
