# Generated by Django 4.1.1 on 2022-09-25 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapi', '0008_alter_hnew_pk_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'story'), ('2', 'job'), ('3', 'comment'), ('4', 'poll'), ('5', 'pollopt')], default=3, max_length=10, verbose_name='article type')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Time Created')),
                ('text', models.CharField(max_length=250, verbose_name='Comment')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapi.ournews', verbose_name='Article')),
            ],
        ),
    ]
